###
POST http://localhost:8080/tasks/restart
Content-Type: application/json

[1,2,3]

###
POST http://localhost:8080/tasks/pause
Content-Type: application/json

[1,2,3]

###
POST http://localhost:8080/tasks/resume
Content-Type: application/json

[225,226,227]

###
POST http://localhost:8080/task/resume
Content-Type: application/x-www-form-urlencoded

id=539

###
POST http://localhost:8080/task/restart
Content-Type: application/x-www-form-urlencoded

id=457

###
POST http://localhost:8080/task/pause
Content-Type: application/x-www-form-urlencoded

id=539


###
#POST http://localhost:8080/tasks/cancel
#Content-Type: application/json
#
#[101,102,103]

####

POST http://localhost:8080/task/cancel
Content-Type: application/x-www-form-urlencoded

id=492

###
#POST http://localhost:8080/thread/update
#Content-Type: application/json
#
#{
#  "taskId": 1,
#  "threadNum": 3
#}
#
#
####
#POST http://localhost:8080/tasks/filter
#Content-Type: application/x-www-form-urlencoded
#
#status=PENDING
#

####
HEAD https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe

####
#POST http://localhost:8080/settings/save
#Content-Type: application/json
#
#{
#  "settingName": "downloadSpeed",
#  "settingValue": "100"
#}
###
POST http://localhost:8080/task/submit
Content-Type: application/x-www-form-urlencoded

url = https://nodejs.org/dist/v12.14.1/node-v12.14.1-x64.msi

####
POST http://localhost:8080/task/submit
Content-Type: application/x-www-form-urlencoded

#url = https://nodejs.org/dist/v12.14.1/node-v12.14.1-x64.msi
url=https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe

###
POST http://localhost:8080/thread/update
Content-Type: application/json

{
  "taskId": 562,
  "threadNum": 7
}