###
POST http://localhost:8080/task/resume
Content-Type: application/x-www-form-urlencoded

id=1

###
POST http://localhost:8080/tasks/restart
Content-Type: application/json

[1,2,3]

###
POST http://localhost:8080/tasks/pause
Content-Type: application/json

[1,2,3]

###
POST http://localhost:8080/tasks/resume
Content-Type: application/json

[1,2,3]

###
POST http://localhost:8080/task/restart
Content-Type: application/x-www-form-urlencoded

id=104

###
POST http://localhost:8080/task/pause
Content-Type: application/x-www-form-urlencoded

id=130

####
POST http://localhost:8080/task/submit
Content-Type: application/x-www-form-urlencoded

//url = https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe
url = https://download-cdn.jetbrains.com/idea/ideaIU-2023.3.2.exe
####
#POST http://localhost:8080/tasks/cancel
#Content-Type: application/json
#
#[101,102,103]

####
#
#POST http://localhost:8080/task/cancel
#Content-Type: application/x-www-form-urlencoded
#
#id=124

####
#POST http://localhost:8080/thread/update
#Content-Type: application/json
#
#{
#  "taskId": 1,
#  "threadNum": 3
#}
#
#
####
#POST http://localhost:8080/tasks/filter
#Content-Type: application/x-www-form-urlencoded
#
#status=Pending
#

####
#GET https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe

####
#POST http://localhost:8080/settings/save
#Content-Type: application/json
#
#{
#  "settingName": "downloadSpeed",
#  "settingValue": "100"
#}

